Repository openwalds/openwald, pull requests merged in 2022-04, with the labels that each got.

#1 create auth module
  auth/kerberos/go.mod
  auth/kerberos/go.sum
  auth/kerberos/krb.go
  auth/kerberos/krb_unix.go
  auth/kerberos/krb_windows.go
Labels: Medium

#2 add conn
  conn.go
  conn_go18.go
  conn_test.go
Labels: Extra Large

#3 add array
  array.go
  array_test.go
Labels: Extra Large, size/XXL

#4 add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/good-first.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/L, Small

#5 add buf
  buf.go
  buf_test.go
Labels: size/L, Small

#6 add connector
  connector.go
  connector_example_test.go
  connector_test.go
Labels: size/L

#7 update readme
  README.md
  uuid.go
  uuid_test.go
Labels: size/M

#9 adjust directory
  pkg/gaussdb/array.go
  pkg/gaussdb/array_test.go
  pkg/gaussdb/auth/kerberos/go.mod
  pkg/gaussdb/auth/kerberos/go.sum
  pkg/gaussdb/auth/kerberos/krb.go
  pkg/gaussdb/auth/kerberos/krb_unix.go
  pkg/gaussdb/auth/kerberos/krb_windows.go
  pkg/gaussdb/buf.go
  pkg/gaussdb/buf_test.go
  pkg/gaussdb/conn.go
  pkg/gaussdb/conn_go18.go
  pkg/gaussdb/conn_test.go
  pkg/gaussdb/connector.go
  pkg/gaussdb/connector_example_test.go
  pkg/gaussdb/connector_test.go
  pkg/gaussdb/uuid.go
  pkg/gaussdb/uuid_test.go
Labels: size/XS

#10 add controller module
  cmd/openwald/main.go
  go.mod
  pkg/controller/health.go
  pkg/controller/health_test.go
  pkg/routes/routes.go
  pkg/routes/routes_test.go
  vendor/gaussdb/array.go
  vendor/gaussdb/array_test.go
  vendor/gaussdb/auth/kerberos/go.mod
  vendor/gaussdb/auth/kerberos/go.sum
  vendor/gaussdb/auth/kerberos/krb.go
  vendor/gaussdb/auth/kerberos/krb_unix.go
  vendor/gaussdb/auth/kerberos/krb_windows.go
  vendor/gaussdb/buf.go
  vendor/gaussdb/buf_test.go
  vendor/gaussdb/conn.go
  vendor/gaussdb/conn_go18.go
  vendor/gaussdb/conn_test.go
  vendor/gaussdb/connector.go
  vendor/gaussdb/connector_example_test.go
  vendor/gaussdb/connector_test.go
  vendor/gaussdb/uuid.go
  vendor/gaussdb/uuid_test.go
  views/health.html
Labels: size/M

#13 add common lib
  hack/lib/env.sh
  hack/lib/logger.sh
  hack/lib/util.sh
  hack/test/run_ut.sh
Labels: size/L

#14 update script
  hack/lib/logger.sh
  hack/lib/util.sh
Labels: size/XS

#15 update lib
  hack/lib/logger.sh
  hack/lib/util.sh
Labels: size/M

#16 update
  .github/workflows/code-check.yml
  .golangci.yml
  hack/lib/util.sh
Labels: size/L

#17 update
  .github/workflows/code-check.yml
  .golangci.yml
  README.md
  hack/lib/util.sh
  pkg/controller/health_test.go
  pkg/gaussdb/array.go
  pkg/gaussdb/array_test.go
  pkg/gaussdb/auth/kerberos/go.mod
  pkg/gaussdb/auth/kerberos/go.sum
  pkg/gaussdb/auth/kerberos/krb.go
  pkg/gaussdb/auth/kerberos/krb_unix.go
  pkg/gaussdb/auth/kerberos/krb_windows.go
  pkg/gaussdb/buf.go
  pkg/gaussdb/buf_test.go
  pkg/gaussdb/conn.go
  pkg/gaussdb/conn_go18.go
  pkg/gaussdb/conn_test.go
  pkg/gaussdb/connector.go
  pkg/gaussdb/connector_example_test.go
  pkg/gaussdb/connector_test.go
  pkg/gaussdb/uuid.go
  pkg/gaussdb/uuid_test.go
Labels: size/XXL

#22 update gitignore
  .github/workflows/.ci.yml.swp
  .gitignore
Labels: size/S

#23 update test script
  hack/lib/env.sh
  hack/test/run_e2e.sh
  hack/test/run_ut.sh
Labels: size/S

#24 update
  .github/workflows/ci.yml
  .github/workflows/code-check.yml
Labels: size/M

#25 update
  .github/workflows/ci.yml
  .github/workflows/code-check.yml
  .golangci.yml
Labels: size/M

#26 test codecheck
  .codespellignore
  .github/workflows/ci.yml
  .github/workflows/code-check.yml
  hack/codecheck/check_codespell.sh
Labels: size/M

#28 update codespell
  .github/config/codespell/.codespellignore
  .github/config/codespell/README.md
  .github/workflows/code-check.yml
Labels: size/S

#29 add licensce
  .github/config/codespell/README.md
  .github/config/license/README.md
  .github/workflows/license.yml
Labels: size/M

#30 update license
  .github/config/license/README.md
  .github/config/license/dependency_decisions.yml
  .github/workflows/license.yml
Labels: size/M

#31 update
  .github/config/license/README.md
Labels: size/S

#32 update
  .github/config/license/README.md
  .github/workflows/code-check.yml
Labels: size/XS

#33 update
  .github/config/license/.licenserc.yml
  .github/config/license/README.md
  .github/workflows/license.yml
  hack/codecheck/check_codespell.sh
  hack/codecheck/check_tab.sh
  hack/lib/env.sh
  hack/lib/logger.sh
  hack/lib/util.sh
  hack/test/run_e2e.sh
  hack/test/run_ut.sh
  pkg/controller/health.go
  pkg/controller/health_test.go
  pkg/routes/routes.go
  pkg/routes/routes_test.go
Labels: size/L

#34 update
  .github/config/license/.licenserc.yml
  .github/config/license/README.md
  hack/codecheck/check_x.sh
Labels: size/L

#35 update
  .github/config/license/README.md
  .github/config/license_finder/README.md
  .github/config/license_finder/dependency_decisions.yml
  .github/config/license_header/.licenserc.yml
  .github/config/license_header/README.md
  .github/workflows/license.yml
Labels: size/L

#37 update
  .github/config/license_header/.licenserc.yml
  hack/codecheck/check_copyright.sh
Labels: size/XS

#41 update
  .github/config/license_finder/README.md
  .github/workflows/license.yml
  docker/Dockerfile
Labels: size/XS

#42 add docker
  .github/workflows/image-dockerhub.yml
  docker/Dockerfile
Labels: size/M

#43 fix bug
  .github/workflows/image-dockerhub.yml
Labels: size/XS

#44 fix bug
  .github/workflows/image-dockerhub.yml
Labels: size/XS

#45 update
  pkg/controller/health.go
  pkg/routes/routes.go
Labels: size/XS

#47 update
  .github/workflows/image-swr.yml
Labels: size/M

#48 update
  .github/workflows/image-swr.yml
Labels: size/XS

#49 update
  .github/workflows/image-swr.yml
Labels: size/XS

#50 update
  .github/workflows/image-latest.yml
Labels: size/M

#51 update
  .github/workflows/ci.yml
  .github/workflows/code-check.yml
  .github/workflows/license.yml
Labels: size/M

#52 update
  .github/workflows/ci.yml
  .github/workflows/code-check.yml
  .github/workflows/license.yml
Labels: size/XS

#53 update
  .github/workflows/image-latest.yml
Labels: size/M

#54 update
  .github/workflows/image-latest.yml
Labels: size/M

#55 update
  .github/workflows/image-latest.yml
Labels: size/S

#56 update
  .github/workflows/image-latest.yml
Labels: size/XS

#57 update
  .github/workflows/image-swr.yml
Labels: size/M

#58 update
  .github/workflows/image-dockerhub.yml
  .github/workflows/image-release.yml
  .github/workflows/image-swr.yml
Labels: size/L

#60 update
  .github/workflows/license.yml
Labels: size/S

#61 update license workflow
  .github/workflows/license.yml
Labels: size/XS

#62 update
  .github/workflows/license.yml
Labels: size/XS

#63 update license env
  .github/workflows/license.yml
Labels: size/S

#64 update
  .github/workflows/release-asset.yml
Labels: size/M

#65 update
  .github/workflows/release-asset.yml
Labels: size/XS

#66 update
  .github/workflows/release-asset.yml
Labels: size/XS

#67 update
  .github/workflows/release-asset.yml
Labels: size/XS

#68 update
  .github/workflows/release-asset.yml
Labels: size/XS

#69 update
  .github/workflows/release-asset.yml
  hack/codecheck/check_tab.sh
Labels: size/M

#70 update
  .github/workflows/release-asset.yml
Labels: size/S

#71 update
  README.md
Labels: size/XS

#72 update
  .github/config/codespell/README.md
  .github/config/license_header/.licenserc.yml
  .golangci.yml
  cmd/openwald/main.go
  hack/codecheck/check_copyright.sh
  hack/codecheck/check_tab.sh
  hack/lib/env.sh
  hack/lib/logger.sh
  hack/lib/util.sh
  hack/test/run_e2e.sh
  hack/test/run_ut.sh
  pkg/controller/health.go
  pkg/controller/health_test.go
  pkg/routes/routes.go
  pkg/routes/routes_test.go
Labels: size/M

#74 update
  .github/workflows/auto-approve.yml
Labels: size/S

#75 update
  .github/workflows/auto-approve.yml
Labels: size/M

#76 update
  .github/workflows/auto-approve.yml
Labels: size/XS

#77 update
  .github/workflows/auto-approve.yml
Labels: size/XS

#78 update
  .github/workflows/auto-approve.yml
Labels: size/XS

#73 update
  README.md
Labels: size/XS

#80 update
  .github/workflows/auto-approve.yml
Labels: size/XS

#79 update
  README.md
Labels: size/XS

#81 update
  .github/workflows/auto-approve.yml
  .github/workflows/ci.yml
  .github/workflows/image-latest.yml
  .github/workflows/image-release.yml
Labels: size/S
